#!/bin/bash
#
# Cloudflare Tunnel Service Installer for Raspberry Pi
# Run with: sudo ./install.sh
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

# Detect architecture
ARCH=$(uname -m)
case "$ARCH" in
    aarch64)
        CF_ARCH="arm64"
        ;;
    armv7l|armv6l)
        CF_ARCH="arm"
        ;;
    x86_64)
        CF_ARCH="amd64"
        ;;
    *)
        log_error "Unsupported architecture: $ARCH"
        exit 1
        ;;
esac

log_info "Detected architecture: $ARCH (cloudflared: $CF_ARCH)"

# Install dependencies
log_info "Installing dependencies..."
apt-get update
apt-get install -y curl jq openssl

# Install cloudflared if not present or update it
log_info "Installing/updating cloudflared..."
CLOUDFLARED_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${CF_ARCH}"

if command -v cloudflared &> /dev/null; then
    CURRENT_VERSION=$(cloudflared --version 2>&1 | head -1 || echo "unknown")
    log_info "Current cloudflared version: $CURRENT_VERSION"
fi

curl -L "$CLOUDFLARED_URL" -o /usr/local/bin/cloudflared
chmod +x /usr/local/bin/cloudflared

NEW_VERSION=$(cloudflared --version 2>&1 | head -1)
log_info "Installed cloudflared version: $NEW_VERSION"

# Create directories
log_info "Creating directories..."
mkdir -p /etc/cf-tunnel
mkdir -p /var/lib/cf-tunnel
chmod 700 /etc/cf-tunnel
chmod 755 /var/lib/cf-tunnel

# Install provisioner script
log_info "Installing provisioner script..."
cp "$SCRIPT_DIR/cf-tunnel-provisioner.sh" /usr/local/bin/cf-tunnel-provisioner.sh
chmod +x /usr/local/bin/cf-tunnel-provisioner.sh

# Install systemd service
log_info "Installing systemd service..."
cp "$SCRIPT_DIR/cf-tunnel.service" /etc/systemd/system/cf-tunnel.service
systemctl daemon-reload

# Check for configuration
if [[ ! -f /etc/cf-tunnel/config.env ]]; then
    log_warn "Configuration file not found!"
    
    # Check for encrypted config
    if [[ -f "$SCRIPT_DIR/config.env.age" ]]; then
        echo ""
        log_info "Found encrypted config: config.env.age"
        read -p "Decrypt it now? (y/n): " DECRYPT_CONFIG
        
        if [[ "$DECRYPT_CONFIG" =~ ^[Yy]$ ]]; then
            # Check for age
            if ! command -v age &> /dev/null; then
                log_info "Installing age encryption tool..."
                apt-get install -y age || {
                    log_error "Failed to install age. Install manually: apt install age"
                }
            fi
            
            if command -v age &> /dev/null; then
                # Try to find or get key
                AGE_KEY=""
                for key_path in "$HOME/.age/key.txt" "/etc/cf-tunnel/age-key.txt" "$SCRIPT_DIR/.age-key.txt"; do
                    if [[ -f "$key_path" ]]; then
                        AGE_KEY="$key_path"
                        break
                    fi
                done
                
                if [[ -z "$AGE_KEY" ]]; then
                    echo ""
                    read -p "Enter path to age private key: " AGE_KEY
                fi
                
                if [[ -f "$AGE_KEY" ]]; then
                    age -d -i "$AGE_KEY" "$SCRIPT_DIR/config.env.age" > /etc/cf-tunnel/config.env
                    chmod 600 /etc/cf-tunnel/config.env
                    log_info "Config decrypted successfully!"
                else
                    log_error "Key file not found: $AGE_KEY"
                fi
            fi
        fi
    fi
fi

# Still no config? Interactive setup
if [[ ! -f /etc/cf-tunnel/config.env ]]; then
    # Interactive configuration
    echo ""
    read -p "Would you like to configure the tunnel now? (y/n): " CONFIGURE
    
    if [[ "$CONFIGURE" =~ ^[Yy]$ ]]; then
        echo ""
        log_info "Starting interactive configuration..."
        echo ""
        
        read -p "Enter your Cloudflare API Token: " CF_API_TOKEN
        read -p "Enter your Cloudflare Account ID: " CF_ACCOUNT_ID
        read -p "Enter your Cloudflare Zone ID: " CF_ZONE_ID
        read -p "Enter your domain (e.g., example.com): " CF_DOMAIN
        read -p "Enter node prefix (default: rpi): " NODE_PREFIX
        NODE_PREFIX="${NODE_PREFIX:-rpi}"
        
        cat > /etc/cf-tunnel/config.env << EOF
# Cloudflare Tunnel Configuration
# Generated by installer on $(date)

CF_API_TOKEN="${CF_API_TOKEN}"
CF_ACCOUNT_ID="${CF_ACCOUNT_ID}"
CF_ZONE_ID="${CF_ZONE_ID}"
CF_DOMAIN="${CF_DOMAIN}"
NODE_PREFIX="${NODE_PREFIX}"
SSH_PORT="22"
ADDITIONAL_SERVICES=""
EOF
        
        chmod 600 /etc/cf-tunnel/config.env
        log_info "Configuration saved to /etc/cf-tunnel/config.env"
    else
        log_info "Copying example configuration..."
        cp "$SCRIPT_DIR/config.env.example" /etc/cf-tunnel/config.env
        chmod 600 /etc/cf-tunnel/config.env
        log_warn "Please edit /etc/cf-tunnel/config.env with your settings"
    fi
else
    log_info "Configuration file already exists at /etc/cf-tunnel/config.env"
fi

# Enable and optionally start service
echo ""
read -p "Enable service to start on boot? (y/n): " ENABLE_SERVICE
if [[ "$ENABLE_SERVICE" =~ ^[Yy]$ ]]; then
    systemctl enable cf-tunnel.service
    log_info "Service enabled"
fi

read -p "Start the service now? (y/n): " START_SERVICE
if [[ "$START_SERVICE" =~ ^[Yy]$ ]]; then
    if [[ -f /etc/cf-tunnel/config.env ]] && grep -q "your-api-token-here" /etc/cf-tunnel/config.env 2>/dev/null; then
        log_error "Configuration still contains placeholder values!"
        log_warn "Please edit /etc/cf-tunnel/config.env first, then run: sudo systemctl start cf-tunnel"
    else
        systemctl start cf-tunnel.service
        sleep 3
        
        if systemctl is-active --quiet cf-tunnel.service; then
            log_info "Service started successfully!"
            
            # Show connection info
            if [[ -f /var/lib/cf-tunnel/tunnel-info.json ]]; then
                echo ""
                log_info "Tunnel Information:"
                HOSTNAME=$(jq -r '.hostname' /var/lib/cf-tunnel/tunnel-info.json)
                echo "  SSH Command: cloudflared access ssh --hostname $HOSTNAME"
                echo "  Or via browser: https://$HOSTNAME (if Access is configured)"
            fi
        else
            log_error "Service failed to start. Check logs with: journalctl -u cf-tunnel -f"
        fi
    fi
fi

echo ""
log_info "Installation complete!"
echo ""
echo "Useful commands:"
echo "  sudo systemctl status cf-tunnel      # Check service status"
echo "  sudo journalctl -u cf-tunnel -f      # View logs"
echo "  sudo systemctl restart cf-tunnel     # Restart service"
echo "  cat /var/lib/cf-tunnel/tunnel-info.json  # View tunnel info"
echo ""
echo "To connect via SSH:"
echo "  cloudflared access ssh --hostname <hostname>"
echo ""
